---
- name: start slapd
  systemd:
    name: slapd
    state: started
    enabled: yes
    daemon_reload: yes

# LDAP file imports
# TODO: Make them vars and pass info based on var relating to file
- name: Load ldap db_config
  shell:
    cmd: ldapadd -Y EXTERNAL -H ldapi:/// -f db.ldif
    chdir: '{{ ldap_dir }}'

- name: Load ldap monitor.ldif
  shell:
    cmd: ldapadd -Y EXTERNAL -H ldapi:/// -f monitor.ldif
    chdir: '{{ ldap_dir }}'

- name: Load ldap base
  shell:
    cmd: ldapadd -x -D "cn=ldapadm,dc={{ short_domain }},dc={{ long_domain.split('.')[1] }}" -f base.ldif -w "{{ ldap_passwd }}"
    chdir: '{{ ldap_dir }}'

- name: Load ldap group
  shell:
    cmd: ldapadd -x -D "cn=ldapadm,dc={{ short_domain }},dc={{ long_domain.split('.')[1] }}" -f group.ldif -w "{{ ldap_passwd }}"
    chdir: '{{ ldap_dir }}'

- name: Load ldap user
  shell:
    cmd: ldapadd -x -D "cn=ldapadm,dc={{ short_domain }},dc={{ long_domain.split('.')[1] }}" -f ldapuser.ldif -w "{{ ldap_passwd }}"
    chdir: '{{ ldap_dir }}'

- name: Import schemas
  shell:
    cmd: ldapadd -Y EXTERNAL -H ldapi:/// -f '/etc/openldap/schema/{{ item }}'
  with_items: '{{ list_of_schemas }}'
