---
- name: Install KDC Packages
  yum:
    name: "{{ packages }}" 
  vars:
    packages:
    - krb5-server
    - krb5-libs
    - krb5-workstation 

# Kerberos Firewall ports
- name: KDC Firewall Rules
  firewalld:
    port: '{{ item }}/tcp'
    permanent: yes
    state: enabled
  with_items:
    - '{{ k_admin_port }}'
    - '{{ kdc_port }}'

# Kerberos Confs
- name: Template for krb5.conf
  template:
    src: templates/krb5.j2
    dest: /etc/krb5.conf
    owner: root
    group: root
    mode: '0644'

# Dir for Kerberos acls
- name: Ensure krb5kdc dir exists
  file:
    path: /var/kerberos/krb5kdc/
    state: directory
    mode: '0755'

# Kerberos Confs
- name: Template for kdc.conf
  template:
    src: templates/kdc.j2
    dest: /var/kerberos/krb5kdc/kdc.conf
    owner: root
    group: root
    mode: '0644'

# Principals that can access KDC db
- name: Template for kadm5.acl
  template:
    src: templates/kadm5.j2
    dest: /var/kerberos/krb5kdc/kadm5.acl
    owner: root
    group: root
    mode: '0644'

- name:  Log into to KDC server to finish setup
  debug: 
    msg: "Run kdb5_util create -s on KDC server"
