---
- name: Install KDC Packages
  yum:
    name: "{{ packages }}" 
  vars:
    packages:
    - krb5-server
    - krb5-libs
    - krb5-workstation 

- name: Template for krb5.conf
  template:
    src: templates/krb5.j2
    dest: /etc/krb5.conf
    owner: root
    group: root
    mode: '0644'

- name: Ensure krb5kdc dir exists
  file:
    path: /var/kerberos/krb5kdc/
    state: directory
    mode: '0755'

- name: Template for kdc.conf
  template:
    src: templates/kdc.j2
    dest: /var/kerberos/krb5kdc/kdc.j2
    owner: root
    group: root
    mode: '0644'
