- name: Install phpldapadmin Packages
  yum:
    name: ['epel-release', 'php-ldap', 'php-mbstring',
      'php-pear', 'php-xml', 'phpldapadmin']
    state: present
 

# Firewall
- name: LDAP Firewall Rules
  firewalld:
    port: "{{ ldap_gui_port }}/tcp"
    permanent: yes
    immediate: yes
    state: enabled
    zone: public

- name: Push out httpd phpadmin conf
  copy:
    src: files/phpldapadmin.conf
    dest: /etc/httpd/conf.d/phpldapadmin.conf
    owner: apache
    group: apache
    mode: "0644"
  notify:
    - start httpd
   
- name: Push out phpadmin config
  template:
    src: templates/phpconfig.j2
    dest: /etc/phpldapadmin/config.php
    owner: apache
    group: apache
    mode: "0640"

- name: start httpd
  systemd:
    name: httpd
    state: started
    enabled: yes
    daemon_reload: yes

