---
# Packages
- name: Install LDAP Packages
  yum:
    name: ['openldap', 
           'openldap-clients', 
           'openldap-servers', 
           'openldap-servers-sql', 
           'openldap-devel', 
           'compat-openldap', 
           'nss-pam-ldapd']
    state: present
  notify:
    - Import schemas


# Firewall
- name: LDAP Firewall Rules
  firewalld:
    port: "{{ ldap_port }}/tcp"
    permanent: yes
    immediate: yes
    state: enabled
    zone: public

