
- name: Push out the Reset Script
  hosts: rhce_clients
  vars:
    vgs_to_remove: ['vg_one', 'vg_two']
    device_to_remove: /dev/sdb
    mgmt_interface: mgmt

  tasks:
    - name: Template Script
      template:
        src: "{{ playbook_dir }}/reset.sh"
        dest: "{{ playbook_dir }}/templated_reset.sh"
      delegate_to: 127.0.0.1

    - name: Push Script
      script: "{{ playbook_dir }}/templated_reset.sh {{ reset_args|default('-h') }}"
      args:
        chdir: /var/tmp
      register: script_output

    - name: Remove VG's
      lvg:
        vg: "{{ item }}"
        state: absent
        force: yes
      loop: "{{ vgs_to_remove }}"
      when: remove_vgs is defined

    - name: Find partitions
      parted:
        device: "{{ device_to_remove }}"
      register: part_info

    - name: Remove Parts
      parted:
        device: "{{ device_to_remove }}"
        number: "{{ item.num }}"
        state: absent
      loop: "{{ part_info.partitions }}"
      when: remove_parts is defined

    - name: Show Results
      debug:
        msg: "{{ script_output.stdout_lines }}"
