---

- name: Install KDC Packages
  yum:
    name: "{{ packages }}" 
  vars:
    packages:
    - krb5-server
    - krb5-libs
    - krb5-workstation 

# Kerberos Firewall ports
- name: KDC Firewall Rules
  firewalld:
    port: '{{ item }}/tcp'
    permanent: yes
    immediate: yes
    state: enabled
    zone: public
  with_items:
    - '{{ k_admin_port }}'
    - '{{ kdc_port }}'

