---
- name: Install basic Packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - vim-enhanced

- name: Test Ansible Variables
  debug: 
    msg: 
    - "Test {{ ansible_domain }}"

- name: Template hosts file
  template:
    src: templates/hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: '0600'
