---
- import_tasks: vim.yml

- name: Set Hostname and fqdn based on Ansible Inventory
  command: hostnamectl set-hostname '{{ inventory_hostname }}.{{ long_domain }}'
  when: (ansible_hostname not in inventory_hostname) or
        (ansible_domain not in long_domain)

- name: Template hosts file
  template:
    src: templates/hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: '0600'

- name: Copy screenrc
  copy:
    src: files/screenrc
    dest: /etc/screenrc

- name: Copy profile.d scripts
  copy:
    src: "files/{{ item }}"
    dest: /etc/profile.d/
  with_items:
    - 99_vim.sh
    - 99_prompt.sh
    - 00_alias.sh



