---
- name: Install basic Packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - vim-enhanced
    - screen
    - mlocate
    - bash-completion

- name: Template hosts file
  template:
    src: templates/hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: '0600'

- name: Copy screenrc
  copy:
    src: files/screenrc
    dest: /etc/screenrc

# Kerberos Confs
- name: Template for krb5.conf
  template:
    src: templates/krb5.j2
    dest: /etc/krb5.conf
    owner: root
    group: root
    mode: '0644'

