---

- name: Install basic Packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - vim-enhanced
    - screen
    - mlocate
    - bash-completion
    - git


- name: Install Vundle
  script: get_vundle.sh

- name: vimrc
  copy:
    src: files/vimrc
    dest: /etc/vimrc
    mode: '0644'
  notify:
    - load vim plugins
