---
- name: Install LDAP Packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - openldap
    - openldap-clients
    - openldap-servers
    - openldap-servers-sql
    - openldap-devel
    - compat-openldap
    - nss-pam-ldapd
    - mod_ldap
